rules:
  - name: prefer-local-short
    when:
      input_tokens_max: 800
      latency_budget_ms_min: 500
    action: local
  - name: send-to-cloud-complex
    when:
      input_tokens_min: 1200
      require_tools: true
    action: cloud
fallback:
  on_local_failure: cloud
  on_cloud_timeout: local_summarized





